### ISSUE TITLE
The remote file either doesn't exist

### ISSUE THREAD

**Issue by Roberto-Gentili** [egor-tensin/setup-mingw#1]
Hi, there is a problem from three hours ago
![image](https://user-images.githubusercontent.com/91185696/135506204-38fe915a-3441-4173-87a6-9856e2c09fce.png)

**Comment by egor-tensin** [comment]
Please re-run your workflow. You can see that it failed to download the distribution from SourceForge (`The operation has timed out` error). I'll fix it so that that kind of error fails the workflow at that point.

**Comment by Roberto-Gentili** [comment]
Solved thanks! I want to ask you something off topic: how can I compile my project and generate a working file also on ARM by using gcc? Can it be done on Windows or Linux?

**Comment by egor-tensin** [comment]
@Roberto-Gentili I'm sorry, I have no experience targetting Windows on ARM.
